name: Gitleaks Secret Scan

on: [push]

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - name: Check out source code
        uses: actions/checkout@v4

      - name: Install Gitleaks
        run: |
          curl -sSfL https://github.com/zricethezav/gitleaks/releases/latest/download/gitleaks-linux-amd64.tar.gz | tar xz
          chmod +x gitleaks

      - name: Run Gitleaks Scan
        run: ./gitleaks detect --source . --exit-code 1 --redact --verbose
